XBRL_TAGS = {
    # -------------------- INCOME STATEMENT --------------------
    "income_stmt_Revenue": {
        "tag": "Revenues",
        "description": "Total revenue generated by the company from its main business operations for the fiscal year. It represents the top line of the income statement and indicates the scale of operations. Unit: USD.",
        "theme": "Growth",
        "unit": "USD"
    },
    "income_stmt_Cost of Revenue": {
        "tag": "CostOfRevenue",
        "description": "Total cost incurred to produce goods or services sold during the fiscal year. Used to calculate Gross Profit. Lower cost relative to revenue indicates better efficiency. Unit: USD.",
        "theme": "Profitability",
        "unit": "USD"
    },
    "income_stmt_Gross Profit": {
        "tag": "GrossProfit",
        "description": "Gross Profit = Revenue − Cost of Revenue. Indicates how much profit is generated before operating expenses. Higher margin means better efficiency in producing goods/services. Unit: USD.",
        "theme": "Profitability",
        "unit": "USD"
    },
    "income_stmt_Operating Expenses": {
        "tag": "OperatingExpenses",
        "description": "Expenses related to core business operations excluding cost of revenue (e.g., SG&A, R&D). Helps calculate Operating Income. Unit: USD.",
        "theme": "Profitability",
        "unit": "USD"
    },
    "income_stmt_Interest Expense": {
        "tag": "InterestExpense",
        "description": "Cost of borrowed funds during the fiscal year. Impacts net income and financial leverage. Unit: USD.",
        "theme": "Leverage",
        "unit": "USD"
    },
    "income_stmt_Provision for Income Tax": {
        "tag": "IncomeTaxExpenseBenefit",
        "description": "Income tax expense recognized during the fiscal year. Used in calculating Net Income. Unit: USD.",
        "theme": "Profitability",
        "unit": "USD"
    },
    "income_stmt_Net Income": {
        "tag": "NetIncomeLoss",
        "description": "Net Income = Total Revenue − Total Expenses − Taxes. Shows overall profitability for the fiscal year. Unit: USD. Typical benchmark: Positive net income indicates profit; negative indicates loss.",
        "theme": "Profitability",
        "unit": "USD"
    },

    # -------------------- BALANCE SHEET --------------------
    "balance_sheet_Current Assets": {
        "tag": "AssetsCurrent",
        "description": "Assets expected to be converted into cash or used up within one year (e.g., cash, inventory, receivables). Used in liquidity ratios like Current Ratio. Unit: USD. Ideal Current Ratio: 1.2–2.0.",
        "theme": "Liquidity",
        "unit": "USD"
    },
    "balance_sheet_Total Assets": {
        "tag": "Assets",
        "description": "Total resources owned by the company with economic value. Used in calculating ROA and debt ratios. Unit: USD.",
        "theme": "Growth",
        "unit": "USD"
    },
    "balance_sheet_Current Liabilities": {
        "tag": "LiabilitiesCurrent",
        "description": "Obligations due within one year (e.g., accounts payable, short-term debt). Used in liquidity ratios. Unit: USD.",
        "theme": "Liquidity",
        "unit": "USD"
    },
    "balance_sheet_Total Liabilities": {
        "tag": "Liabilities",
        "description": "Total obligations of the company arising from past transactions. Used in leverage ratios like Debt-to-Assets and Debt-to-Equity. Unit: USD.",
        "theme": "Leverage",
        "unit": "USD"
    },
    "balance_sheet_Stockholders Equity": {
        "tag": "StockholdersEquity",
        "description": "Residual interest in the company's assets after deducting liabilities. Used in ROE and Debt-to-Equity ratio calculations. Unit: USD.",
        "theme": "Leverage",
        "unit": "USD"
    },

    # -------------------- CASH FLOW --------------------
    "cash_flow_Operating Cash Flow": {
        "tag": "NetCashProvidedByUsedInOperatingActivities",
        "description": "Cash generated or used by core business operations. Indicates ability to generate cash from operations. Unit: USD.",
        "theme": "Cash Flow",
        "unit": "USD"
    },
    "cash_flow_Investing Cash Flow": {
        "tag": "NetCashProvidedByUsedInInvestingActivities",
        "description": "Cash used for investing activities (buying/selling assets, acquisitions). Negative cash flow can indicate growth investment. Unit: USD.",
        "theme": "Cash Flow",
        "unit": "USD"
    },
    "cash_flow_Financing Cash Flow": {
        "tag": "NetCashProvidedByUsedInFinancingActivities",
        "description": "Cash from financing activities (debt, equity issuance, dividends). Shows how a company funds operations and growth. Unit: USD.",
        "theme": "Cash Flow",
        "unit": "USD"
    },

    # -------------------- DERIVED METRICS --------------------
    "Return on Assets (ROA) %": {
        "description": "ROA = Net Income ÷ Total Assets × 100. Measures efficiency of using assets to generate profit. Higher ROA indicates better asset utilization. Unit: %",
        "theme": "Profitability",
        "unit": "%"
    },
    "Return on Equity (ROE) %": {
        "description": "ROE = Net Income ÷ Stockholders Equity × 100. Measures how effectively equity is used to generate profit. Unit: %",
        "theme": "Profitability",
        "unit": "%"
    },
    "Gross Profit Margin %": {
        "description": "Gross Profit ÷ Revenue × 100. Shows profitability after cost of goods sold. Higher margin = more efficient operations. Unit: %",
        "theme": "Profitability",
        "unit": "%"
    },
    "Operating Margin %": {
        "description": "Operating Income ÷ Revenue × 100. Shows efficiency of core business operations excluding taxes and interest. Unit: %",
        "theme": "Profitability",
        "unit": "%"
    },
    "Net Profit Margin %": {
        "description": "Net Income ÷ Revenue × 100. Shows overall profitability relative to revenue. Unit: %",
        "theme": "Profitability",
        "unit": "%"
    },
    "Current Ratio": {
        "description": "Current Assets ÷ Current Liabilities. Measures liquidity; ability to cover short-term obligations. Ideal range: 1.2–2.0. Unit: ratio",
        "theme": "Liquidity",
        "unit": "ratio"
    },
    "Debt to Assets Ratio %": {
        "description": "Total Liabilities ÷ Total Assets × 100. Measures leverage; higher means more debt relative to assets. Unit: %",
        "theme": "Leverage",
        "unit": "%"
    },
    "Debt to Equity Ratio %": {
        "description": "Total Liabilities ÷ Stockholders Equity × 100. Measures financial leverage relative to equity. Unit: %",
        "theme": "Leverage",
        "unit": "%"
    },
    "Operating CF to Current Liabilities": {
        "description": "Operating Cash Flow ÷ Current Liabilities. Shows ability to cover short-term obligations with cash from operations. Unit: ratio",
        "theme": "Liquidity",
        "unit": "ratio"
    },
    "Operating CF to Net Income": {
        "description": "Operating Cash Flow ÷ Net Income. Indicates quality of earnings; >1 means cash exceeds accounting profit. Unit: ratio",
        "theme": "Cash Flow",
        "unit": "ratio"
    },
    "Free Cash Flow": {
        "description": "Free Cash Flow = Operating Cash Flow − Investing Cash Flow. Represents cash available for dividends, debt repayment, or growth. Unit: USD",
        "theme": "Cash Flow",
        "unit": "USD"
    }
}


# AWS
AWS_PROFILE = "Finsights"
S3_BUCKET = "sentence-data-ingestion"
S3_FOLDER = "QuantitativeData"

# Notifications
SNS_TOPIC_ARN = "arn:aws:sns:us-east-1:123456789012:finsights-alerts"
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/XXXX/YYYY/ZZZZ"

# User-Agent
USER_AGENT = "Karthik Raja (University Project; karthikraja.ai.project@gmail.com)"